### ISSUE TITLE
Create Continuous Integration Deployment

### ISSUE THREAD

**Issue by carsongee** [mitodl/lmod_proxy#29]
It is convenient for integration and system testing to have an installation of the application that is always running the latest master version of the repo that works.  We can add this easily with Travis as a step to do after a successful test has occurred.  It does this by packaging our app up into a heroku deployable unit, and pushing it.

**Comment by pdpinch** [comment]
Thanks for the clarification. 

So this will help with https://trello.com/c/62hVeCCB/281-1-lmod-proxy-deploy-our-own-version-off-ike-s-server ?

(as an aside, I'm thinking it might me help track PRs if the corresponding issue includes a link to the Trello card)

**Comment by carsongee** [comment]
No card for this, just general improvement to development automation and system testing
