### ISSUE TITLE
Transmit raw score and max score to remote gradebook

### ISSUE THREAD

**Issue by pwilkins** [mitodl/lmod_proxy#36]
Currently lmod_proxy sends calculated scores to the remote gradebook.  The requested change is to send the raw score and the max score.

To send the max score, the assignment must be created by lmod_proxy.  (In the existing implementation, assignments are created in the body of the PyLmod call that sends scores to the remote gradebook.)

**Comment by pdpinch** [comment]
Can you point to the code in PyLmod that create the assignment?

**Comment by pwilkins** [comment]
@pdpinch https://github.com/mitodl/PyLmod/blob/master/pylmod/gradebook.py#L918

Note that it inconveniently sets default values for ``maxpoints`` and ``weight``.

**Comment by pdpinch** [comment]
oy

So I know I said I didn't want to change pylmod, but wouldn't it be a lot easier and a lot better to change this to do something more normal?

**Comment by pwilkins** [comment]
"Normal".  I've heard of it.  What would be more normal in this case?

**Comment by pdpinch** [comment]
I don't think this function should be setting a default value for `maxpoints`. If we can omit it, we should. If there must be a value, it seems to me it should be set in the library, not in this one function call. 

That all said, I'm not sure if this is on the critical path for addressing our issue. If I'm complicating things, feel free to set my suggestions aside for now.

**Comment by pwilkins** [comment]
I agree that setting default values here is questionable at best and an unfortunate expedient at worst.  Knowing what we know now I'd like to change it.  

My intent is making a separate ``create_assignment()`` call before execution reaches this code.  The existence of the assignment will remove this code from the path of execution.

**Comment by pdpinch** [comment]
I agree with your plan. More so now that I've seen the code.

**Comment by pdpinch** [comment]
@noisecapella I didn't get a chance to bring up this issue, but might you have some time to work on it with @pwilkins after you've wrapped up your Teacher's Portal items?

**Comment by noisecapella** [comment]
Will do

**Comment by noisecapella** [comment]
Why aren't we just changing pylmod again? It's well tested already and we can add a flag to `spreadsheet2gradebook` to preserve backwards compatibility for existing users. cc @pdpinch
