### ISSUE TITLE
explicity set isGradeApproved when setting a grade

### ISSUE THREAD

**Issue by pdpinch** [mitodl/lmod_proxy#5]
In the current version of [Grades2Stellar](https://github.com/mitocw/grades2stellar/blob/master/stellargradebook.py#L344), there is no value set for isGradeApproved when setting a student's grade. 

This should be explicitly set to false or, even better, the API should pass a value through. 

This will help us address issues like [Zendesk #1435](https://odl.zendesk.com/agent/tickets/1435).

Hmmm. Maybe this needs to be an issue on https://github.com/mitodl/PyLmod

**Comment by carsongee** [comment]
It needs to be an issue in all three repos, this, pylmod and edx-platform

**Comment by pwilkins** [comment]
In pylmod, it would be a one-line fix to set ```isGradeApproved``` to ```False``` by default here: https://github.com/mitodl/PyLmod/blob/master/pylmod/gradebook.py#L156

**Comment by pdpinch** [comment]
@pwilkins go for it: https://github.com/mitodl/PyLmod/issues/28

**Comment by pdpinch** [comment]
@carsongee does it need to be an issue in edX platform because we need to expose a UI?

**Comment by carsongee** [comment]
As discussed in person, you are right about why it needs to be exposed, but I think for now we can make it configurable setting (after it is added to pylmod)

**Comment by pwilkins** [comment]
I asked the LMod team for the default value of ``isGradeApproved``.  They responded, "Actually, this field is required, and the grade will not save if it is not provided."
