### ISSUE TITLE
conditionally set grades, to avoid overriding manually set grades

### ISSUE THREAD

**Issue by pdpinch** [mitodl/lmod_proxy#6]
I'm not sure if this is an issue for lmod_proxy, or for pylmod. 

I'd like to an option for setting grades to be conditional -- only set the grade if one hasn't been set already. 

This would avoid overriding grades that have been set manually in the gradebook, and may obviate the immediate need for #5 (even though it's still a good idea).

**Comment by carsongee** [comment]
this is pylmod too, I would just need to swap out for multigrade statement for the new one here

**Comment by carsongee** [comment]
Just thinking about this more per our conversation this morning, and you wouldn't want this "always on/off" so for edx-platform we wouldn't be able to implement this without adding checkboxes to the from in the legacy dashboard.  As a result, I think this is ultimately blocked by not having that feature migrated to the current dashboard, and when we do that we will probably want to rethink a lot of how this app works.

**Comment by pdpinch** [comment]
This app has been retired and we will archive the repo.
