### ISSUE TITLE
Upgrade to Python 3

### ISSUE THREAD

**Issue by blarghmatey** [mitodl/lmod_proxy#62]
With the official end of life for Python 2 at the end of this year we should upgrade this app to run on Python 3

**Comment by markbreedlove** [comment]
This issue includes updating dependencies, too.

**Comment by markbreedlove** [comment]
This will include releasing a new version of `PyLmod` (see https://github.com/mitodl/PyLmod/pull/75) and pushing it to PyPI.

**Comment by markbreedlove** [comment]
`PyLmod` and `lmod_proxy` have had new releases, and now the only thing remaining is to run the deployment on Open Shift.

**Comment by markbreedlove** [comment]
I have this running in QA now.
I will post something outside of this public channel on how to test it.

**Comment by markbreedlove** [comment]
The remaining steps are:
* Have Meredith look at the app our QA site.
* Update our documentation with instructions on how to do Openshift deployments for this project.
